# Generated by Django 4.2.6 on 2023-10-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.AddField(
            model_name="appointment",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointment",
            name="bank_address",
            field=models.CharField(default="123 Main Street", max_length=255),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(max_length=100),
        ),
    ]
