# Generated by Django 4.2.6 on 2023-10-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_remove_appointment_date_appointment_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
